package net.bible.sharedui.strings

import android.content.Context
import net.bible.android.activity.R

/** R.string-backed [Strings]. Grows alongside the commonMain interface as leaves move. */
class AndroidStrings(private val context: Context) : Strings {
    override val calcWrongFormat: String get() = context.getString(R.string.calc_wrong_format)
    override val calcWrongFormatOperand: String get() = context.getString(R.string.calc_wrong_format_operand)
    override val calcDivisionByZero: String get() = context.getString(R.string.calc_division_by_zero)
    override fun historyFor(workspace: String, window: Int): String =
        context.getString(R.string.history_for, workspace, window)
    override val errorOccurred: String get() = context.getString(R.string.error_occurred)
    override val okay: String get() = context.getString(R.string.okay)
    override val indexingWaitMsg: String get() = context.getString(R.string.indexing_wait_msg)
    override val noTasksRunning: String get() = context.getString(R.string.no_tasks_running)
    override val doInBackground: String get() = context.getString(R.string.do_in_background)
    override val readingPlanSelectorTitle: String get() = context.getString(R.string.rdg_plan_selector_title)
    override val readingPlanTitle: String get() = context.getString(R.string.rdg_plan_title)
    override val planDuplicateUserPlan: String get() = context.getString(R.string.plan_duplicate_user_plan)
    override val resetGeneric: String get() = context.getString(R.string.reset_generic)
    override val resetPlanQuestion: String get() = context.getString(R.string.reset_plan_question)
    override val yes: String get() = context.getString(R.string.yes)
    override val no: String get() = context.getString(R.string.no)
    override val all: String get() = context.getString(R.string.all)
    override val setCurrentDay: String get() = context.getString(R.string.set_current_day)
    override val setStartDate: String get() = context.getString(R.string.rdg_plan_set_start_date)
    override val importReadingPlan: String get() = context.getString(R.string.import_reading_plan)
    override val setCurrentDayQuestion: String get() = context.getString(R.string.msg_set_current_day_reading_plan)
    override val selectPassage: String get() = context.getString(R.string.selectPassage)
    override val speak: String get() = context.getString(R.string.speak)
    override val stop: String get() = context.getString(R.string.stop)
    override val pause: String get() = context.getString(R.string.pause)
    override val done: String get() = context.getString(R.string.done)

    // Batch 12f — reading-view Speak transport bar
    override val bookmarks: String get() = context.getString(R.string.bookmarks)
    override val rewind: String get() = context.getString(R.string.rewind)
    override val forward: String get() = context.getString(R.string.forward)
    override val speakNext: String get() = context.getString(R.string.speak_next)
    override val speakPrevious: String get() = context.getString(R.string.speak_previous)
    override val speakBookmarksMenuTitle: String get() = context.getString(R.string.speak_bookmarks_menu_title)

    override val generalBookTitle: String get() = context.getString(R.string.general_book)
    override val mapTitle: String get() = context.getString(R.string.doc_type_map)
    override val dictionaryTitle: String get() = context.getString(R.string.dictionary)
    override val searchHint: String get() = context.getString(R.string.search)
    override val bible: String get() = context.getString(R.string.bible)
    override val deuterocanonical: String get() = context.getString(R.string.deuterocanonical)
    override val menuAlphabetical: String get() = context.getString(R.string.sort_by_alphabetical)
    override val menuRowOrder: String get() = context.getString(R.string.book_menu_sort_row_opt)
    override val menuGroupByCategory: String get() = context.getString(R.string.book_menu_group_by_category)
    override val menuShowLongName: String get() = context.getString(R.string.book_menu_show_long_book_name)
    override val menuShowProgressBars: String get() = context.getString(R.string.book_menu_show_progress_bars)

    // Batch 4 — document selection
    override fun docFilterResults(count: Int): String = context.getString(R.string.document_filter_results, count)
    override val docTypeAll: String get() = context.getString(R.string.doc_type_all)
    override val docTypeBible: String get() = context.getString(R.string.doc_type_bible)
    override val docTypeCommentary: String get() = context.getString(R.string.doc_type_commentary)
    override val docTypeDictionary: String get() = context.getString(R.string.doc_type_dictionary)
    override val docTypeGeneralBook: String get() = context.getString(R.string.doc_type_book)
    override val docTypeMaps: String get() = context.getString(R.string.doc_type_map)
    override val docTypeAddon: String get() = context.getString(R.string.doc_type_addons)
    override val languageLabel: String get() = context.getString(R.string.chooce_language_hint)
    override val documentTypeLabel: String get() = context.getString(R.string.document_type_label)
    override val aboutDoc: String get() = context.getString(R.string.about)
    override val deleteLabel: String get() = context.getString(R.string.delete)
    override val deleteIndexLabel: String get() = context.getString(R.string.delete_index)
    override val unlockModule: String get() = context.getString(R.string.unlock_module)
    override fun deleteDoc(name: String): String = context.getString(R.string.delete_doc, name)
    override fun deleteSearchIndexDoc(name: String): String = context.getString(R.string.delete_search_index_doc, name)
    override val cantDeleteDocument: String get() = context.getString(R.string.cant_delete_document)
    override val downloadDocuments: String get() = context.getString(R.string.download)

    // Batch 4b — download
    override fun moduleSizeMb(mb: Double): String = context.getString(R.string.module_size_megabytes, mb)
    override val cancel: String get() = context.getString(R.string.cancel)

    // Settings editor sheets T5 — SettingsEditorSheet header
    override val settingsEditorBack: String get() = context.getString(R.string.settings_editor_back)
    override val settingsEditorClose: String get() = context.getString(R.string.settings_editor_close)
    override val settingsEditorApply: String get() = context.getString(R.string.settings_editor_apply)

    // Batch 5 — search
    override val search: String get() = context.getString(R.string.search)
    override val emptyList: String get() = context.getString(R.string.empty_list)
    override val searchIndex: String get() = context.getString(R.string.search_index)
    override val searchSettings: String get() = context.getString(R.string.search_settings)
    override val allWords: String get() = context.getString(R.string.search_all_words)
    override val anyWord: String get() = context.getString(R.string.search_any_word)
    override val phrase: String get() = context.getString(R.string.search_phrase)
    override val searchAllBible: String get() = context.getString(R.string.search_all_bible)
    override val searchOldTestament: String get() = context.getString(R.string.search_old_testament)
    override val searchNewTestament: String get() = context.getString(R.string.search_new_testament)
    override val searchCurrentBook: String get() = context.getString(R.string.search_current_book)
    override val searchWhere: String get() = context.getString(R.string.search_bible_section_group_prompt)
    override val chooseTranslations: String get() = context.getString(R.string.search_translations)
    override val recentSearches: String get() = context.getString(R.string.recent_searches)
    override val create: String get() = context.getString(R.string.index_create)
    override val rebuildIndex: String get() = context.getString(R.string.rebuild_index)
    override val openResultsInWindow: String get() = context.getString(R.string.open_in_window)
    override fun createIndexFor(documentName: String): String =
        context.getString(R.string.create_index_for, documentName)
    override fun rebuildIndexFor(documentName: String): String =
        context.getString(R.string.rebuild_index_for, documentName)
    override val rebuildIndexButton: String get() = context.getString(R.string.rebuild_index_button)

    // F6 — the reading toolbar's search mode
    override val searchClose: String get() = context.getString(R.string.search_close)
    override val searchOptions: String get() = context.getString(R.string.search_options)
    override val searchSubmit: String get() = context.getString(R.string.search_submit)
    override val searchClear: String get() = context.getString(R.string.search_clear)
    override val helpSearchText2: String get() = context.getString(R.string.help_search_text2)
    override fun helpSearchDetails(link: String): String =
        context.getString(R.string.help_search_details, link)
    override val helpApacheLucene: String get() = context.getString(R.string.help_apache_lucene)
    override val menu: String get() = context.getString(R.string.menu)
    override val searchIndexingThenSearch: String get() = context.getString(R.string.search_indexing_then_search)
    override fun searchNotAvailableForDocument(name: String): String =
        context.getString(R.string.search_not_available_for_document, name)
    override val searchNotAvailable: String get() = context.getString(R.string.search_not_available)

    // Batch 5 (Plan B) — EPUB search
    override val ftsQuery: String get() = context.getString(R.string.search_fts_query)
    override val helpFts5: String get() = context.getString(R.string.help_fts5)
    override fun searchIn(docAbbrev: String): String = context.getString(R.string.search_in, docAbbrev)
    override fun searchWithResults2(count: String, docAbbrev: String): String =
        context.getString(R.string.search_with_results2, count, docAbbrev)

    // Batch 4 (remainder) — MyDocuments
    override val myDocumentsEmpty: String get() = context.getString(R.string.my_documents_empty)
    override val saveAndExit: String get() = context.getString(R.string.save_and_exit)
    override val dismiss: String get() = context.getString(R.string.dismiss)
    override val newItem: String get() = context.getString(R.string.new_item)
    override val importDocument: String get() = context.getString(R.string.my_document_import_document)
    override val importPage: String get() = context.getString(R.string.my_document_import_page)
    override val newPageTitle: String get() = context.getString(R.string.my_document_create_page_title)
    override val export: String get() = context.getString(R.string.export)
    override val rename: String get() = context.getString(R.string.rename)
    override val exportDocumentLabel: String get() = context.getString(R.string.my_document_export_document)
    override val editDescriptionLabel: String get() = context.getString(R.string.my_document_edit_description)
    override val noDescription: String get() = context.getString(R.string.my_document_no_description)
    override val createTitle: String get() = context.getString(R.string.my_document_create_title)
    override val renameTitle: String get() = context.getString(R.string.my_document_rename_title)
    override val pageRenameTitle: String get() = context.getString(R.string.my_document_page_rename_title)
    override val contentTypeLabel: String get() = context.getString(R.string.my_document_content_type_label)
    override val cannotDeleteAiDocuments: String get() = context.getString(R.string.my_document_cannot_delete_ai_documents)
    override fun newDocumentName(n: Int): String = context.getString(R.string.my_document_new_name, n)
    override fun newPageName(n: Int): String = context.getString(R.string.my_document_new_page_name, n)
    override fun deleteDocumentConfirmation(name: String): String = context.getString(R.string.my_document_delete_confirmation, name)
    override fun deletePageConfirmation(name: String): String = context.getString(R.string.my_document_page_delete_confirmation, name)
    override val deleteDocumentsConfirmation: String get() = context.getString(R.string.delete_docs_confirm)
    override val deletePagesConfirmation: String get() = context.getString(R.string.my_document_pages_delete_confirmation)

    // Batch 4 remainder — cloud documents management
    override val cloudStatusSynced: String get() = context.getString(R.string.cloud_doc_status_synced)
    override val cloudStatusLocalOnly: String get() = context.getString(R.string.cloud_doc_status_local_only)
    override val cloudStatusCloudOnly: String get() = context.getString(R.string.cloud_doc_status_cloud_only)
    override val cloudStatusUpdate: String get() = context.getString(R.string.cloud_doc_status_update)
    override val cloudStatusBlocked: String get() = context.getString(R.string.cloud_doc_status_blocked)
    override val cloudStatusWontSync: String get() = context.getString(R.string.cloud_doc_status_wont_sync)
    override val cloudStatusRemoved: String get() = context.getString(R.string.cloud_doc_status_removed)
    override val cloudStatusStillInstalled: String get() = context.getString(R.string.cloud_doc_status_still_installed)
    override val cloudActionDownload: String get() = context.getString(R.string.cloud_doc_action_download)
    override val cloudActionPush: String get() = context.getString(R.string.cloud_doc_action_push)
    override val cloudActionRemoveCloud: String get() = context.getString(R.string.cloud_doc_action_remove_cloud)
    override val cloudActionRemoveAllDevices: String get() = context.getString(R.string.cloud_doc_action_remove_all_devices)
    override val cloudActionBlock: String get() = context.getString(R.string.cloud_doc_action_block)
    override val cloudActionDontSync: String get() = context.getString(R.string.cloud_doc_action_dont_sync)
    override val cloudActionUnblock: String get() = context.getString(R.string.cloud_doc_action_unblock)
    override val cloudActionAllowSync: String get() = context.getString(R.string.cloud_doc_action_allow_sync)
    override val cloudActionRestore: String get() = context.getString(R.string.cloud_doc_action_restore)
    override val cloudActionPurge: String get() = context.getString(R.string.cloud_doc_action_purge)
    override fun cloudVersionPrefix(version: String): String = context.getString(R.string.cloud_doc_version_prefix, version)

    // Speak (Batch 6a)
    override val speakTitle: String get() = context.getString(R.string.speak)
    override val playbackSettingsTitle: String get() = context.getString(R.string.playback_settings_title)
    override val confChangeChapter: String get() = context.getString(R.string.conf_change_chapter)
    override val confChangeTitle: String get() = context.getString(R.string.conf_change_title)
    override val confSpeakFootnotes: String get() = context.getString(R.string.conf_speak_footnotes)
    override val speakSpeedTitle: String get() = context.getString(R.string.speak_speed_title)
    override val repeatPassage: String get() = context.getString(R.string.repeat_passage)
    override val setRepeatPassageRange: String get() = context.getString(R.string.set_repeat_passage_range)
    override val speakSleepTimerTitle: String get() = context.getString(R.string.speak_sleep_timer_title)
    override val confSpeakSleepTimer: String get() = context.getString(R.string.conf_speak_sleep_timer)
    override val speakAdvancedSettings: String get() = context.getString(R.string.speak_advanced_settings)
    override val systemSpeakSettings: String get() = context.getString(R.string.system_speak_settings)
    override val helpLabel: String get() = context.getString(R.string.help)
    override fun speakSleepTimerMinutes(minutes: Int): String =
        context.getString(R.string.speak_sleep_timer_minutes, minutes)
    override val speakSleepTimerCustom: String get() = context.getString(R.string.speak_sleep_timer_custom)
    override val speakSleepTimerOff: String get() = context.getString(R.string.speak_sleep_timer_off)
    override val speakOtherSettings: String get() = context.getString(R.string.speak_other_settings)
    override val speakVerseRangeToRepeat: String get() = context.getString(R.string.speak_verse_range_to_repeat)

    override val speakBeginningOfPassage: String get() = context.getString(R.string.speak_beginning_of_passage)
    override val speakEndingOfPassage: String get() = context.getString(R.string.speak_ending_of_passage)
    override val speakEndingVerseMustBeLater: String get() = context.getString(R.string.speak_ending_verse_must_be_later)
    override val sleepTimerTitle: String get() = context.getString(R.string.sleep_timer_title)

    override val speakSettingsTitle: String get() = context.getString(R.string.speak_settings_title)
    override val confSpeakSynchronize: String get() = context.getString(R.string.conf_speak_synchronize)
    override val confReplaceDivinename: String get() = context.getString(R.string.conf_replace_divinename)
    override val speakBookmarkingSettingsTitle: String get() = context.getString(R.string.speak_bookmarking_settings_title)
    override val confSpeakAutoBookmark: String get() = context.getString(R.string.conf_speak_auto_bookmark)
    override val confSavePlaybackSettingsToBookmarks: String get() = context.getString(R.string.conf_save_playback_settings_to_bookmarks)

    // Batch 6b — WorkspaceSelector
    override val workspaceSelectorTitle: String get() = context.getString(R.string.workspace_selector_title)
    override val giveNameWorkspace: String get() = context.getString(R.string.give_name_workspace)
    override val newCopiedWorkspace: String get() = context.getString(R.string.new_copied_workspace)
    override val deleteWorkspaceLabel: String get() = context.getString(R.string.delete_workspace)
    override val workspaceSettingsLabel: String get() = context.getString(R.string.workspace_settings)
    override val copyWorkspaceSettings: String get() = context.getString(R.string.copy_workspace_settings)
    override val copySettingsToWorkspaces: String get() = context.getString(R.string.copy_settings_to_workspaces)
    override val copySettingsToGlobalDefaults: String get() = context.getString(R.string.copy_settings_to_global_defaults)
    override val menuBack: String get() = context.getString(R.string.menu_back)
    override val copySettingsTitle: String get() = context.getString(R.string.copy_settings_title)
    override val copySettingsWorkspacesTitle: String get() = context.getString(R.string.copy_settings_workspaces_title)
    override val selectAll: String get() = context.getString(R.string.select_all)
    override val selectNone: String get() = context.getString(R.string.select_none)
    override val workspaceSaveChanges: String get() = context.getString(R.string.workspace_save_changes)
    override fun workspaceNumber(n: Int) = context.getString(R.string.workspace_number, n)
    override fun copyOfWorkspace(name: String) = context.getString(R.string.copy_of_workspace, name)
    override fun workspaceListingWithCurrent(name: String) = context.getString(R.string.workspace_listing_with_current, name)

    // Batch 9a — AiConnectionSettingsScreen custom editors
    override val resetToDefault: String get() = context.getString(R.string.reset_to_default)
    override val rawLogRetentionDisabledLabel: String get() = context.getString(R.string.raw_log_retention_summary_disabled)

    // Batch 9b — AiProvidersScreen
    override val aiProvidersTitle: String get() = context.getString(R.string.ai_providers_category)
    override val addProvider: String get() = context.getString(R.string.ai_add_provider)
    override val providerEditTitle: String get() = context.getString(R.string.ai_provider_edit)
    override val providerApiKeyNotSet: String get() = context.getString(R.string.ai_provider_api_key_not_set)
    override fun providerApiKeyMasked(label: String, suffix: String): String =
        context.getString(R.string.ai_provider_api_key_masked, label, suffix)
    override val providerSelectType: String get() = context.getString(R.string.ai_provider_select_type)
    override val providerNameLabel: String get() = context.getString(R.string.ai_provider_name)
    override val providerNameHint: String get() = context.getString(R.string.ai_provider_name_hint)
    override val providerApiKeyLabel: String get() = context.getString(R.string.ai_provider_api_key)
    override val providerEndpointLabel: String get() = context.getString(R.string.ai_provider_endpoint)
    override val providerEndpointHint: String get() = context.getString(R.string.ai_provider_endpoint_hint)
    override val providerEndpointDescription: String get() = context.getString(R.string.ai_provider_endpoint_description)
    override val providerApiFormatLabel: String get() = context.getString(R.string.ai_provider_api_format)
    override fun providerDeleteConfirm(name: String): String = context.getString(R.string.ai_provider_delete_confirm, name)
    override val apiKeyInstructionsPrefix: String get() = context.getString(R.string.easy_setup_api_key_instructions)

    // Batch 9b — AiModelsScreen
    override val aiModelsTitle: String get() = context.getString(R.string.ai_models_category)
    override val addModel: String get() = context.getString(R.string.add_model)
    override val editModelTitle: String get() = context.getString(R.string.edit_model_title)
    override fun modelDeleteConfirm(name: String): String = context.getString(R.string.model_delete_confirm, name)
    override val modelSetDefault: String get() = context.getString(R.string.model_set_default)
    override val modelSelectProviderLabel: String get() = context.getString(R.string.model_select_provider)
    override val modelSupportedBadge: String get() = context.getString(R.string.model_supported_badge)
    override val showUnsupportedModels: String get() = context.getString(R.string.show_also_unsupported_models)
    override val llmCustomModel: String get() = context.getString(R.string.llm_custom_model)
    override val llmCustomModelHint: String get() = context.getString(R.string.llm_custom_model_dialog_message)
    override val llmCustomInputPriceLabel: String get() = context.getString(R.string.llm_custom_input_price_title)
    override val llmCustomOutputPriceLabel: String get() = context.getString(R.string.llm_custom_output_price_title)
    override val llmOpenrouterModelLabel: String get() = context.getString(R.string.llm_openrouter_model)
    override val llmOpenrouterCategoryLabel: String get() = context.getString(R.string.llm_openrouter_category)
    override val llmOpenrouterCategoryAll: String get() = context.getString(R.string.llm_openrouter_category_all)

    // Batch 9b — EasySetupWizard (Task 6)
    override val easySetupTitle: String get() = context.getString(R.string.easy_setup_title)
    override val easySetupEnterApiKey: String get() = context.getString(R.string.easy_setup_enter_api_key)
    override val easySetupTestConnection: String get() = context.getString(R.string.easy_setup_test_connection)
    override val easySetupTesting: String get() = context.getString(R.string.easy_setup_testing)
    override val easySetupSuccess: String get() = context.getString(R.string.easy_setup_success)
    override fun easySetupFailed(message: String): String = context.getString(R.string.easy_setup_failed, message)
    override val easySetupDoneTitle: String get() = context.getString(R.string.easy_setup_done_title)
    override val easySetupDoneMessage: String get() = context.getString(R.string.easy_setup_done_message)

    // Batch 9c — ToolPermissionList
    override val toolOptionEnabled: String get() = context.getString(R.string.tool_option_enabled)
    override val toolOptionDisabled: String get() = context.getString(R.string.tool_option_disabled)
    override val toolOptionAllow: String get() = context.getString(R.string.permission_option_always_allow)
    override val toolOptionDeny: String get() = context.getString(R.string.permission_option_always_deny)
    override val toolOptionAsk: String get() = context.getString(R.string.permission_status_default)
    override val toolOptionDefaultEnabled: String get() = context.getString(R.string.tool_option_default_enabled)
    override val toolOptionDefaultDisabled: String get() = context.getString(R.string.tool_option_default_disabled)
    override val toolOptionDefaultAllowed: String get() = context.getString(R.string.tool_option_default_allowed)
    override val toolOptionDefaultDenied: String get() = context.getString(R.string.tool_option_default_denied)
    override val toolDescriptionInfoContentDescription: String get() = context.getString(R.string.tool_description_info)

    // Task E2 — ToolPermissionList CategoryHeader bulk read/write toggles (F35/F37)
    override val toolCategoryReadLabel: String get() = context.getString(R.string.tool_category_read)
    override val toolCategoryWriteLabel: String get() = context.getString(R.string.tool_category_write)

    // Batch 9c — AiPromptsScreen (prompt manager)
    override val aiPromptsTitle: String get() = context.getString(R.string.ai_settings)
    override val aiSetupTitle: String get() = context.getString(R.string.ai_setup_title)
    override val aiSetupDescription: String get() = context.getString(R.string.ai_setup_description)
    override val aiConfigureButton: String get() = context.getString(R.string.ai_configure_button)
    override val managePromptsSummary: String get() = context.getString(R.string.manage_prompts_summary)
    override val newPrompt: String get() = context.getString(R.string.new_prompt)
    override val newCategory: String get() = context.getString(R.string.new_category)
    override val connectionSettingsMenuLabel: String get() = context.getString(R.string.ai_connection_settings)
    override val exportPromptsCsv: String get() = context.getString(R.string.export_prompts_csv)
    override val importPromptsCsv: String get() = context.getString(R.string.import_prompts_csv)
    override val restoreHiddenPromptsLabel: String get() = context.getString(R.string.ai_restore_hidden_prompts)
    override val promptCategoryFavorites: String get() = context.getString(R.string.prompt_category_favorites)
    override val promptCategoryUncategorized: String get() = context.getString(R.string.prompt_category_uncategorized)
    override val hiddenSuffix: String get() = context.getString(R.string.hidden)
    override val hideCategoryLabel: String get() = context.getString(R.string.hide_category)
    override val showCategoryLabel: String get() = context.getString(R.string.show_category)
    override val moveUpLabel: String get() = context.getString(R.string.move_category_up)
    override val moveDownLabel: String get() = context.getString(R.string.move_category_down)
    override val deleteCategoryLabel: String get() = context.getString(R.string.delete_category)
    override fun deleteCategoryConfirm(name: String): String = context.getString(R.string.delete_category_confirm_title, name)
    override val deleteCategoryKeepPromptsLabel: String get() = context.getString(R.string.delete_category_keep_prompts)
    override val deleteCategoryAndPromptsLabel: String get() = context.getString(R.string.delete_category_and_prompts)
    override val hidePromptLabel: String get() = context.getString(R.string.ai_hide_prompt)
    override val restoreLabel: String get() = context.getString(R.string.restore)
    override val deletePromptConfirmMessage: String get() = context.getString(R.string.delete_prompt_confirm_message)
    override val moveToCategoryLabel: String get() = context.getString(R.string.move_to_category)

    // Batch 12e-A — reading-view AI dialogs (LlmDialogHelper) + Plan B agent-log panel
    override val selectLlmPrompt: String get() = context.getString(R.string.select_llm_prompt)
    override val specifyBeforeRunTitle: String get() = context.getString(R.string.specify_before_run_title)
    override val specifyBeforeRunHint: String get() = context.getString(R.string.specify_before_run_hint)
    override val selectModelBeforeRunTitle: String get() = context.getString(R.string.select_model_before_run_title)
    override val setDefaultModelForPrompt: String get() = context.getString(R.string.set_default_model_for_prompt)
    override val aiRegenerateTitle: String get() = context.getString(R.string.ai_regenerate_title)
    override val aiRegenerateInstructionsHint: String get() = context.getString(R.string.ai_regenerate_instructions_hint)
    override val aiRegenerateKeepPrevious: String get() = context.getString(R.string.ai_regenerate_keep_previous)
    override val aiRegenerateFreshRun: String get() = context.getString(R.string.ai_regenerate_fresh_run)
    override val aiDocumentRegenerate: String get() = context.getString(R.string.ai_document_regenerate)
    override val aiDocumentRegenerating: String get() = context.getString(R.string.ai_document_regenerating)
    override val agentLogIdle: String get() = context.getString(R.string.agent_log_idle)
    override val agentLogModelNotConfigured: String get() = context.getString(R.string.agent_log_model_not_configured)
    override val agentLogSelectModel: String get() = context.getString(R.string.agent_log_select_model)
    override val agentLogViewRaw: String get() = context.getString(R.string.agent_log_view_raw)
    override val agentLogStop: String get() = context.getString(R.string.agent_log_stop)
    override val agentLogClose: String get() = context.getString(R.string.agent_log_close)
    override val agentLogExpand: String get() = context.getString(R.string.agent_log_expand)
    override val aiTaskCompleted: String get() = context.getString(R.string.ai_task_completed)
    override fun agentLogModelSelector(model: String): String = context.getString(R.string.agent_log_model_selector, model)

    // Batch 9c — PromptEditScreen (Task 6)
    override val promptTabPrompt: String get() = context.getString(R.string.prompt_tab_prompt)
    override val promptTabPermissions: String get() = context.getString(R.string.prompt_tab_permissions)
    override val promptTabAdvanced: String get() = context.getString(R.string.prompt_tab_advanced)
    override val promptNameLabel: String get() = context.getString(R.string.prompt_name)
    override val promptDescriptionLabel: String get() = context.getString(R.string.prompt_description)
    override val promptTemplateLabel: String get() = context.getString(R.string.prompt_template)
    override val promptShowInLabel: String get() = context.getString(R.string.prompt_show_in)
    override val promptContextVerseSelection: String get() = context.getString(R.string.prompt_context_verse_selection)
    override val promptContextTextSelection: String get() = context.getString(R.string.prompt_context_text_selection)
    override val promptContextWindowMenu: String get() = context.getString(R.string.prompt_context_window_menu)
    override val promptContextWorkspaceMenu: String get() = context.getString(R.string.prompt_context_workspace_menu)
    override val promptContextNoteEditor: String get() = context.getString(R.string.prompt_context_note_editor)
    override val promptBibleOnlyLabel: String get() = context.getString(R.string.prompt_bible_only)
    override val promptIsTextTransformationLabel: String get() = context.getString(R.string.prompt_is_text_transformation)
    override val promptIsTextTransformationDescription: String get() = context.getString(R.string.prompt_is_text_transformation_description)
    override val promptCategoryLabel: String get() = context.getString(R.string.prompt_category)
    override val categoryNoneLabel: String get() = context.getString(R.string.category_none)
    override val promptPermissionModeLabel: String get() = context.getString(R.string.prompt_permission_mode)
    override val promptPermissionUseDefault: String get() = context.getString(R.string.prompt_permission_use_default)
    override val permissionAlwaysAsk: String get() = context.getString(R.string.permission_always_ask)
    override val permissionAskOncePerRun: String get() = context.getString(R.string.permission_ask_once_per_run)
    override val permissionAllowAll: String get() = context.getString(R.string.permission_allow_all)
    override val permissionDenyAll: String get() = context.getString(R.string.permission_deny_all)
    override val resetToolPermissionsLabel: String get() = context.getString(R.string.reset_all_permissions)
    override val promptModelOverrideLabel: String get() = context.getString(R.string.prompt_model_override)
    override val promptMaxIterationsLabel: String get() = context.getString(R.string.prompt_max_iterations)
    override val promptMaxIterationsHint: String get() = context.getString(R.string.prompt_max_iterations_hint)
    override val promptStrictContextMatchingLabel: String get() = context.getString(R.string.prompt_strict_context_matching)
    override val promptStrictContextMatchingDescription: String get() = context.getString(R.string.prompt_strict_context_matching_description)
    override val promptSpecifyBeforeRunLabel: String get() = context.getString(R.string.prompt_edit_before_run)
    override val promptSpecifyBeforeRunDescription: String get() = context.getString(R.string.prompt_edit_before_run_description)
    override val promptNoDocumentCreationLabel: String get() = context.getString(R.string.prompt_no_document_creation)
    override val promptNoDocumentCreationDescription: String get() = context.getString(R.string.prompt_no_document_creation_description)
    override val promptAutoIncludeDocumentsLabel: String get() = context.getString(R.string.prompt_auto_include_documents)
    override val promptAutoIncludeDocumentsDescription: String get() = context.getString(R.string.prompt_auto_include_documents_description)
    override val promptAutoIncludeCommentariesLabel: String get() = context.getString(R.string.prompt_auto_include_commentaries)
    override val promptAutoIncludeCommentariesDescription: String get() = context.getString(R.string.prompt_auto_include_commentaries_description)
    override val promptEditTitleEdit: String get() = context.getString(R.string.edit_prompt)
    override val promptEditTitleBuiltIn: String get() = context.getString(R.string.built_in_prompt)
    override val copyToCustomizeLabel: String get() = context.getString(R.string.copy_to_customize)
    override val viewToolsMenuLabel: String get() = context.getString(R.string.ai_available_tools)
    override val discardChangesConfirmation: String get() = context.getString(R.string.discard_changes_confirmation)

    // Batch 9d — GlobalToolPermissionsScreen + ToolInfoScreen
    override val globalToolPermissionsTitle: String get() = context.getString(R.string.global_tool_permissions_title)
    override val aiReadToolsLabel: String get() = context.getString(R.string.ai_read_tools)
    override val aiWriteToolsLabel: String get() = context.getString(R.string.ai_write_tools)

    // Batch 9d — AiDocumentFilterScreen
    override val aiDocumentFilterTitle: String get() = context.getString(R.string.ai_document_filter_activity_title)

    // Batch 9d — RawLogHistoryScreen + RawLlmLogScreen
    override val rawLogHistoryTitle: String get() = context.getString(R.string.raw_log_history_title)
    override val rawLogHistoryEmpty: String get() = context.getString(R.string.raw_log_history_empty)
    override val rawLogDeleteSelectedLabel: String get() = context.getString(R.string.raw_log_delete_selected)
    override val rawLogDeleteOld: String get() = context.getString(R.string.raw_log_delete_old)
    override val rawLogOlder1Week: String get() = context.getString(R.string.raw_log_older_1_week)
    override val rawLogOlder1Month: String get() = context.getString(R.string.raw_log_older_1_month)
    override val rawLogOlder3Months: String get() = context.getString(R.string.raw_log_older_3_months)
    override val rawLogDeleteAll: String get() = context.getString(R.string.raw_log_delete_all)
    override val rawLogErrorIndicator: String get() = context.getString(R.string.raw_log_error_indicator)
    override val rawLlmLogEmpty: String get() = context.getString(R.string.raw_llm_log_empty)
    override val copyLabel: String get() = context.getString(R.string.copy)
    override val shareLabel: String get() = context.getString(R.string.share)
    override val reportBugLabel: String get() = context.getString(R.string.ai_bug_report_menu)
    override val areYouSure: String get() = context.getString(R.string.are_you_sure)

    // Batch 9 fix B3 — AI language picker Compose dialog (F32)
    override val aiLanguageCustomHint: String get() = context.getString(R.string.ai_language_custom_hint)

    // Batch 9 fix B1 — AI disclaimer info dialog (F28). `aiDisclaimerBody` is a DEFAULT member on
    // the `Strings` interface itself (composed from the 12 parts below) — see its kdoc — so it is
    // deliberately NOT overridden here.
    override val disclaimerWarningSummary: String get() = context.getString(R.string.ai_disclaimer_warning_summary)
    override val aiDisclaimerDialogTitle: String get() = context.getString(R.string.ai_disclaimer_dialog_title)
    override val aiDisclaimerIntro: String get() = context.getString(R.string.ai_disclaimer_intro)
    override val aiDisclaimerApproach: String get() = context.getString(R.string.ai_disclaimer_approach)
    override val aiDisclaimerResponsibility: String get() = context.getString(R.string.ai_disclaimer_responsibility)
    override val aiDisclaimerPoint1: String get() = context.getString(R.string.ai_disclaimer_point1)
    override val aiDisclaimerPoint2: String get() = context.getString(R.string.ai_disclaimer_point2)
    override val aiDisclaimerPoint3: String get() = context.getString(R.string.ai_disclaimer_point3)
    override val aiDisclaimerPoint4: String get() = context.getString(R.string.ai_disclaimer_point4)
    override val aiDisclaimerPoint5: String get() = context.getString(R.string.ai_disclaimer_point5)
    override val aiDisclaimerPoint6: String get() = context.getString(R.string.ai_disclaimer_point6)
    override val aiDisclaimerPoint7: String get() = context.getString(R.string.ai_disclaimer_point7)
    override val aiDisclaimerPoint8: String get() = context.getString(R.string.ai_disclaimer_point8)
    override val aiDisclaimerPoint9: String get() = context.getString(R.string.ai_disclaimer_point9)

    // Batch 9 fix D1 — Quick-setup accept-disclaimer Compose dialog (F31)
    override val aiDisclaimerAcceptTitle: String get() = context.getString(R.string.ai_disclaimer_accept_title)
    override val aiDisclaimerAcceptButton: String get() = context.getString(R.string.ai_disclaimer_accept_button)

    // Batch 9 fix C2 — AiPrompts help dialog "Read more" link (F30)
    override val helpReadMoreLink: String get() = context.getString(R.string.help_read_more_link)

    // Batch 7a — LabelEditScreen
    override val editLabelTitle: String get() = context.getString(R.string.edit_label)
    override val labelNameHint: String get() = context.getString(R.string.label_name_prompt)
    override val selectCustomIconLabel: String get() = context.getString(R.string.select_custom_icon)
    override val favouriteLabelSwitchLabel: String get() = context.getString(R.string.favourite_label)
    override val thisBookmarkSectionTitle: String get() = context.getString(R.string.this_bookmark)
    override val addedToBookmarkLabel: String get() = context.getString(R.string.added_to_bookmark)
    override val primaryLabelSwitchLabel: String get() = context.getString(R.string.primary_label)
    override val thisWorkspaceSectionTitle: String get() = context.getString(R.string.this_workspace)
    override val autoAssignLabelSwitchLabel: String get() = context.getString(R.string.auto_assign_labels1)
    override val autoAssignPrimaryLabelSwitchLabel: String get() = context.getString(R.string.auto_assign_labels_primary)
    override val overrideStyleFieldLabel: String get() = context.getString(R.string.override_style)
    override val noOverrideSuffix: String get() = context.getString(R.string.no_override_suffix)
    override val displayModeHighlight: String get() = context.getString(R.string.display_mode_highlight)
    override val displayModeUnderline: String get() = context.getString(R.string.display_mode_underline)
    override val displayModeMarker: String get() = context.getString(R.string.display_mode_marker)
    override val displayModeHidden: String get() = context.getString(R.string.display_mode_hidden)
    override val displayModeInherit: String get() = context.getString(R.string.display_mode_inherit)

    // Batch 7b-1 — ManageLabelsScreen
    override val labelsSearchHint: String get() = context.getString(R.string.labels_search_hint)
    override val activeLabelsHeader: String get() = context.getString(R.string.active_labels)
    override val recentLabelsHeader: String get() = context.getString(R.string.recent_labels)
    override val otherLabelsHeader: String get() = context.getString(R.string.other_labels)
    override val overrideIndicatorDescription: String get() = context.getString(R.string.workspace_override_indicator)

    // Batch 7b-2 — ManageLabelsScreen StudyPad content-search + export/import
    override val searchModeNameStart: String get() = context.getString(R.string.search_mode_name_start)
    override val searchModeNameContains: String get() = context.getString(R.string.search_mode_name_contains)
    override val searchModeContent: String get() = context.getString(R.string.search_mode_content)
    override val searchResultsMatch: String get() = context.getString(R.string.search_results_match)
    override fun searchResultsMatches(count: Int): String = context.getString(R.string.search_results_matches, count)
    override val studyPadsLabel: String get() = context.getString(R.string.studypads)
    override fun exportSomething(what: String): String = context.getString(R.string.export_something, what)
    override fun importItems(what: String): String = context.getString(R.string.import_items, what)

    // Batch 7c — BookmarksScreen
    override val manageLabelsLabel: String get() = context.getString(R.string.manage_labels)
    override val sortByBibleBookLabel: String get() = context.getString(R.string.sort_by_bible_book)
    override val sortByDateLabel: String get() = context.getString(R.string.sort_by_date)
    override val showNotesLabel: String get() = context.getString(R.string.show_notes)
    override val assignLabelsLabel: String get() = context.getString(R.string.assign_labels)
    override val bookmarksSearchNotesHint: String get() = context.getString(R.string.filter_by_notes)

    // Batch 8 — ReadingProgress (Reading tab)
    override val readingProgressTitle: String get() = context.getString(R.string.reading_progress_title)
    override val readingProgressChaptersRead: String get() = context.getString(R.string.reading_progress_chapters_read)
    override val readingProgressActiveDays: String get() = context.getString(R.string.reading_progress_active_days)
    override fun readingProgressOverall(pct: Float): String =
        context.getString(R.string.reading_progress_overall, String.format("%.1f", pct))
    override fun readingProgressCycle(cycle: Int): String =
        context.getString(R.string.reading_progress_cycle, cycle)
    override val readingProgressNewCycle: String get() = context.getString(R.string.reading_progress_new_cycle)
    override val readingProgressNewCycleConfirm: String get() = context.getString(R.string.reading_progress_new_cycle_confirm)
    override val readingProgressPercentReadScale: String get() = context.getString(R.string.reading_progress_percent_read_scale)
    override val readingProgressReadCountScale: String get() = context.getString(R.string.reading_progress_read_count_scale)
    override fun readingProgressPercentLabel(pct: Int): String =
        context.getString(R.string.reading_progress_percent_label, pct)
    override fun readingProgressHistoryFor(subject: String): String =
        context.getString(R.string.reading_progress_history_for, subject)
    override val readingProgressHistoryNoEntries: String get() = context.getString(R.string.reading_progress_history_no_entries)
    override val readingProgressHistoryVersionUnknown: String get() = context.getString(R.string.reading_progress_history_version_unknown)
    override val readingProgressSettings: String get() = context.getString(R.string.reading_progress_settings)
    override val readingProgressBibleHeatmap: String get() = context.getString(R.string.reading_progress_bible_heatmap)
    override val readingProgressOldTestament: String get() = context.getString(R.string.reading_progress_old_testament)
    override val readingProgressNewTestament: String get() = context.getString(R.string.reading_progress_new_testament)
    override val readingProgressCalendar: String get() = context.getString(R.string.reading_progress_calendar)
    override val readingProgressPreviousCycle: String get() = context.getString(R.string.reading_progress_previous_cycle)
    override val readingProgressNextCycle: String get() = context.getString(R.string.reading_progress_next_cycle)
    override val memorizeTabReading: String get() = context.getString(R.string.memorize_tab_reading)
    override val memorizeTabMemorization: String get() = context.getString(R.string.memorize_tab_memorization)

    // Batch 8 — ReadingProgress (Memorize tab)
    override val memorizeVersesMemorized: String get() = context.getString(R.string.memorize_verses_memorized)
    override val memorizeVersesTarget: String get() = context.getString(R.string.memorize_verses_target)
    override fun memorizeShowMore(count: Int): String =
        context.getString(R.string.memorize_show_more, count)
    override fun memorizeConfirmUnmark(name: String): String =
        context.getString(R.string.memorize_confirm_unmark, name)
    override fun memorizeConfirmRemoveTarget(name: String): String =
        context.getString(R.string.memorize_confirm_remove_target, name)
    override val memorizeMemorizedPassages: String get() = context.getString(R.string.memorize_memorized_passages)
    override val memorizeNoMemorizedPassages: String get() = context.getString(R.string.memorize_no_memorized_passages)
    override val memorizeTargets: String get() = context.getString(R.string.memorize_targets)
    override val memorizeNoTargets: String get() = context.getString(R.string.memorize_no_targets)
    override val memorizeViewOverview: String get() = context.getString(R.string.memorize_view_overview)
    override val memorizeViewList: String get() = context.getString(R.string.memorize_view_list)
    override val memorizeCalendar: String get() = context.getString(R.string.memorize_calendar)
    override val help: String get() = context.getString(R.string.help)

    // Batch 11 — startup welcome
    override val welcomeDownloadButton: String get() = context.getString(R.string.download)
    override val welcomeImportButton: String get() = context.getString(R.string.install_zip)
    override val welcomeRestoreButton: String get() = context.getString(R.string.restore_database)
    override val welcomeRedownloadButton: String get() = context.getString(R.string.redownload_documents)
    override val welcomeEasyStartButton: String get() = context.getString(R.string.easy_start_title)
    override val welcomeHomepageLabel: String get() = context.getString(R.string.homepage)
    override val welcomeGithubLabel: String get() = context.getString(R.string.github_page)

    // Task B1 (InstallZip Plan B) — Compose install UI
    override val installZipTitle: String get() = context.getString(R.string.install_zip)
    override fun installDoYouWant(subject: String): String = context.getString(R.string.install_do_you_want, subject)
    override val proceed: String get() = context.getString(R.string.proceed)
    override val overwriteFilesTitle: String get() = context.getString(R.string.overwrite_files_title)
    override fun overwriteFiles(files: String): String = context.getString(R.string.overwrite_files, files)
    override val epubUpgradeTitle: String get() = context.getString(R.string.bookmark_warning)
    override val epubUpgradeWarning: String get() = context.getString(R.string.bookmark_warning2)
    override val epubUpgradeRecommendation: String get() = context.getString(R.string.bookmark_warning4)
    override val epubUpgradeQuestion: String get() = context.getString(R.string.bookmark_warning3)

    // Batch 13 T2 — CustomRepositories list + CustomRepositoryEditor screens
    override val customRepositories: String get() = context.getString(R.string.custom_repositories)
    override val customRepositoriesGuidance: String get() = context.getString(R.string.custom_repositories_empty_list_message)
    override val customRepositoriesHelp0: String get() = context.getString(R.string.custom_repositories_help0)
    override val customRepositoriesHelp1: String get() = context.getString(R.string.custom_repositories_help1)
    override fun customRepositoriesHelp2(link: String): String = context.getString(R.string.custom_repositories_help2, link)
    override val wikiPage: String get() = context.getString(R.string.wiki_page)
    override fun deleteCustomRepository(name: String): String = context.getString(R.string.delete_custom_repository, name)
    override fun duplicateCustomRepository(name: String): String = context.getString(R.string.duplicate_custom_repository, name)
    override val repositorySpecification: String get() = context.getString(R.string.repository_specification)
    override val packagesDir: String get() = context.getString(R.string.packages_dir)

    // Batch 13 T5 — BackupRestoreScreen
    override val backupAndRestoreTitle: String get() = context.getString(R.string.backup_and_restore)
    override val backupDatabaseLabel: String get() = context.getString(R.string.backup_database)
    override val backupDatabaseInfo: String get() = context.getString(R.string.backup_database_info)
    override val backupDocumentsLabel: String get() = context.getString(R.string.backup_documents)
    override val backupDocumentsInfo: String get() = context.getString(R.string.backup_document_info)
    override val backupApplicationLabel: String get() = context.getString(R.string.backup_application)
    override val backupApplicationInfo: String get() = context.getString(R.string.backup_application_info)
    override val backupToButton: String get() = context.getString(R.string.backup_to)
    override val restoreOrImportTitle: String get() = context.getString(R.string.backup_restore2)
    override val restoreOrImportFromButton: String get() = context.getString(R.string.backup_restore_from2)
    override val autoBackupsTitle: String get() = context.getString(R.string.auto_backups_title)
    override val resetDatabasesTitle: String get() = context.getString(R.string.reset_databases_title)
    override val resetDatabasesDescription: String get() = context.getString(R.string.reset_databases_description)
    override fun resetSomething(name: String): String = context.getString(R.string.reset_something, name)
    override val lastCrashInfoTitle: String get() = context.getString(R.string.last_crash_info_title)

    // Batch 13 T7 — ProgressStatusComposeActivity
    override val taskKillWarning: String get() = context.getString(R.string.task_kill_warning)

    // --- Agent permissions (Batch Z-early) ---
    override val agentPermissionTitle: String get() = context.getString(R.string.agent_permission_title)
    override fun agentPermissionMessageWithAction(action: String): String =
        context.getString(R.string.agent_permission_message_with_action, action)
    override fun agentPermissionMessage(toolName: String, toolDescription: String): String =
        context.getString(R.string.agent_permission_message, toolName, toolDescription)
    override val permissionAllowOnce: String get() = context.getString(R.string.permission_allow_once)
    override val permissionAllowForSession: String get() = context.getString(R.string.permission_allow_for_session)
    override val permissionAllowAllSession: String get() = context.getString(R.string.permission_allow_all_session)
    override fun permissionAllowAlways(toolName: String): String =
        context.getString(R.string.permission_allow_always, toolName)
    override val permissionDeny: String get() = context.getString(R.string.permission_deny)

    // Batch 4c — colour picker
    override val colorPickerTitle: String get() = context.getString(R.string.color_picker_title)
    override val colorPickerPresets: String get() = context.getString(R.string.color_picker_presets)
    override val colorPickerCustom: String get() = context.getString(R.string.color_picker_custom)

    // Round 8b — document-row markers
    override val recommendedDocument: String get() = context.getString(R.string.recommended_document)
    override val badDocumentWarning: String get() = context.getString(R.string.bad_document_warning)
    override val expandRow: String get() = context.getString(R.string.bookmark_expand_row)
    override val collapseRow: String get() = context.getString(R.string.bookmark_collapse_row)
    override val bookmarkLabelFilter: String get() = context.getString(R.string.bookmark_label_filter)

    // Round 9a Plan B — label style picker
    override val bookmarkStylePreviewSample: String get() = context.getString(R.string.bookmark_style_preview_sample)
    override val bookmarkStyleSectionTitle: String get() = context.getString(R.string.bookmark_style)
    override val bookmarkStyleSelectionHeading: String get() = context.getString(R.string.bookmark_style_selection)
    override val bookmarkStyleWholeVerseHeading: String get() = context.getString(R.string.bookmark_style_whole_verse)
    override val bookmarkStyleWholeVerseCustom: String get() = context.getString(R.string.bookmark_style_whole_verse_custom)

    // Round 14a — dialog-to-sheet conversions
    override val cloudDocSyncNow: String get() = context.getString(R.string.cloud_doc_sync_now)
}
