package net.bible.sharedui.strings

import android.content.Context
import net.bible.android.activity.R

/** R.string-backed [Strings]. Grows alongside the commonMain interface as leaves move. */
class AndroidStrings(private val context: Context) : Strings {
    override val calcWrongFormat: String get() = context.getString(R.string.calc_wrong_format)
    override val calcWrongFormatOperand: String get() = context.getString(R.string.calc_wrong_format_operand)
    override val calcDivisionByZero: String get() = context.getString(R.string.calc_division_by_zero)
    override fun historyFor(workspace: String, window: Int): String =
        context.getString(R.string.history_for, workspace, window)
    override val errorOccurred: String get() = context.getString(R.string.error_occurred)
    override val okay: String get() = context.getString(R.string.okay)
    override val indexingWaitMsg: String get() = context.getString(R.string.indexing_wait_msg)
    override val noTasksRunning: String get() = context.getString(R.string.no_tasks_running)
    override val doInBackground: String get() = context.getString(R.string.do_in_background)
    override val readingPlanSelectorTitle: String get() = context.getString(R.string.rdg_plan_selector_title)
    override val readingPlanTitle: String get() = context.getString(R.string.rdg_plan_title)
    override val planDuplicateUserPlan: String get() = context.getString(R.string.plan_duplicate_user_plan)
    override val resetGeneric: String get() = context.getString(R.string.reset_generic)
    override val resetPlanQuestion: String get() = context.getString(R.string.reset_plan_question)
    override val yes: String get() = context.getString(R.string.yes)
    override val no: String get() = context.getString(R.string.no)
    override val all: String get() = context.getString(R.string.all)
    override val setCurrentDay: String get() = context.getString(R.string.set_current_day)
    override val setStartDate: String get() = context.getString(R.string.rdg_plan_set_start_date)
    override val importReadingPlan: String get() = context.getString(R.string.import_reading_plan)
    override val setCurrentDayQuestion: String get() = context.getString(R.string.msg_set_current_day_reading_plan)
    override val selectPassage: String get() = context.getString(R.string.selectPassage)
    override val speak: String get() = context.getString(R.string.speak)
    override val stop: String get() = context.getString(R.string.stop)
    override val pause: String get() = context.getString(R.string.pause)
    override val done: String get() = context.getString(R.string.done)
    override val generalBookTitle: String get() = context.getString(R.string.general_book)
    override val mapTitle: String get() = context.getString(R.string.doc_type_map)
    override val dictionaryTitle: String get() = context.getString(R.string.dictionary)
    override val searchHint: String get() = context.getString(R.string.search)
    override val bible: String get() = context.getString(R.string.bible)
    override val deuterocanonical: String get() = context.getString(R.string.deuterocanonical)
    override val menuAlphabetical: String get() = context.getString(R.string.sort_by_alphabetical)
    override val menuRowOrder: String get() = context.getString(R.string.book_menu_sort_row_opt)
    override val menuGroupByCategory: String get() = context.getString(R.string.book_menu_group_by_category)
    override val menuShowLongName: String get() = context.getString(R.string.book_menu_show_long_book_name)
    override val menuShowProgressBars: String get() = context.getString(R.string.book_menu_show_progress_bars)

    // Batch 4 — document selection
    override fun docFilterResults(count: Int): String = context.getString(R.string.document_filter_results, count)
    override val docTypeAll: String get() = context.getString(R.string.doc_type_all)
    override val docTypeBible: String get() = context.getString(R.string.doc_type_bible)
    override val docTypeCommentary: String get() = context.getString(R.string.doc_type_commentary)
    override val docTypeDictionary: String get() = context.getString(R.string.doc_type_dictionary)
    override val docTypeGeneralBook: String get() = context.getString(R.string.doc_type_book)
    override val docTypeMaps: String get() = context.getString(R.string.doc_type_map)
    override val docTypeAddon: String get() = context.getString(R.string.doc_type_addons)
    override val languageLabel: String get() = context.getString(R.string.chooce_language_hint)
    override val aboutDoc: String get() = context.getString(R.string.about)
    override val deleteLabel: String get() = context.getString(R.string.delete)
    override val deleteIndexLabel: String get() = context.getString(R.string.delete_index)
    override val unlockModule: String get() = context.getString(R.string.unlock_module)
    override fun deleteDoc(name: String): String = context.getString(R.string.delete_doc, name)
    override fun deleteSearchIndexDoc(name: String): String = context.getString(R.string.delete_search_index_doc, name)
    override val cantDeleteDocument: String get() = context.getString(R.string.cant_delete_document)
    override val downloadDocuments: String get() = context.getString(R.string.download)

    // Batch 4b — download
    override fun moduleSizeMb(mb: Double): String = context.getString(R.string.module_size_megabytes, mb)
    override val cancel: String get() = context.getString(R.string.cancel)

    // Batch 5 — search
    override val search: String get() = context.getString(R.string.search)
    override val emptyList: String get() = context.getString(R.string.empty_list)
    override val searchIndex: String get() = context.getString(R.string.search_index)
    override val allWords: String get() = context.getString(R.string.search_all_words)
    override val anyWord: String get() = context.getString(R.string.search_any_word)
    override val phrase: String get() = context.getString(R.string.search_phrase)
    override val searchAllBible: String get() = context.getString(R.string.search_all_bible)
    override val searchOldTestament: String get() = context.getString(R.string.search_old_testament)
    override val searchNewTestament: String get() = context.getString(R.string.search_new_testament)
    override val searchCurrentBook: String get() = context.getString(R.string.search_current_book)
    override val chooseTranslations: String get() = context.getString(R.string.search_translations)
    override val recentSearches: String get() = context.getString(R.string.recent_searches)
    override val create: String get() = context.getString(R.string.index_create)
    override val rebuildIndex: String get() = context.getString(R.string.rebuild_index)
    override val openResultsInWindow: String get() = context.getString(R.string.open_in_window)
    override fun createIndexFor(documentName: String): String =
        context.getString(R.string.create_index_for, documentName)
    override fun rebuildIndexFor(documentName: String): String =
        context.getString(R.string.rebuild_index_for, documentName)
    override val rebuildIndexButton: String get() = context.getString(R.string.rebuild_index_button)

    // Batch 5 (Plan B) — EPUB search
    override val ftsQuery: String get() = context.getString(R.string.search_fts_query)
    override val helpFts5: String get() = context.getString(R.string.help_fts5)
    override fun searchIn(docAbbrev: String): String = context.getString(R.string.search_in, docAbbrev)
    override fun searchWithResults2(count: String, docAbbrev: String): String =
        context.getString(R.string.search_with_results2, count, docAbbrev)

    // Batch 4 (remainder) — MyDocuments
    override val myDocumentsEmpty: String get() = context.getString(R.string.my_documents_empty)
    override val saveAndExit: String get() = context.getString(R.string.save_and_exit)
    override val dismiss: String get() = context.getString(R.string.dismiss)
    override val newItem: String get() = context.getString(R.string.new_item)
    override val importDocument: String get() = context.getString(R.string.my_document_import_document)
    override val importPage: String get() = context.getString(R.string.my_document_import_page)
    override val newPageTitle: String get() = context.getString(R.string.my_document_create_page_title)
    override val export: String get() = context.getString(R.string.export)
    override val rename: String get() = context.getString(R.string.rename)
    override val exportDocumentLabel: String get() = context.getString(R.string.my_document_export_document)
    override val editDescriptionLabel: String get() = context.getString(R.string.my_document_edit_description)
    override val noDescription: String get() = context.getString(R.string.my_document_no_description)
    override val createTitle: String get() = context.getString(R.string.my_document_create_title)
    override val renameTitle: String get() = context.getString(R.string.my_document_rename_title)
    override val pageRenameTitle: String get() = context.getString(R.string.my_document_page_rename_title)
    override val contentTypeLabel: String get() = context.getString(R.string.my_document_content_type_label)
    override val cannotDeleteAiDocuments: String get() = context.getString(R.string.my_document_cannot_delete_ai_documents)
    override fun newDocumentName(n: Int): String = context.getString(R.string.my_document_new_name, n)
    override fun newPageName(n: Int): String = context.getString(R.string.my_document_new_page_name, n)
    override fun deleteDocumentConfirmation(name: String): String = context.getString(R.string.my_document_delete_confirmation, name)
    override fun deletePageConfirmation(name: String): String = context.getString(R.string.my_document_page_delete_confirmation, name)

    // Batch 4 remainder — cloud documents management
    override val cloudStatusSynced: String get() = context.getString(R.string.cloud_doc_status_synced)
    override val cloudStatusLocalOnly: String get() = context.getString(R.string.cloud_doc_status_local_only)
    override val cloudStatusCloudOnly: String get() = context.getString(R.string.cloud_doc_status_cloud_only)
    override val cloudStatusUpdate: String get() = context.getString(R.string.cloud_doc_status_update)
    override val cloudStatusBlocked: String get() = context.getString(R.string.cloud_doc_status_blocked)
    override val cloudStatusWontSync: String get() = context.getString(R.string.cloud_doc_status_wont_sync)
    override val cloudStatusRemoved: String get() = context.getString(R.string.cloud_doc_status_removed)
    override val cloudStatusStillInstalled: String get() = context.getString(R.string.cloud_doc_status_still_installed)
    override val cloudActionDownload: String get() = context.getString(R.string.cloud_doc_action_download)
    override val cloudActionPush: String get() = context.getString(R.string.cloud_doc_action_push)
    override val cloudActionRemoveCloud: String get() = context.getString(R.string.cloud_doc_action_remove_cloud)
    override val cloudActionRemoveAllDevices: String get() = context.getString(R.string.cloud_doc_action_remove_all_devices)
    override val cloudActionBlock: String get() = context.getString(R.string.cloud_doc_action_block)
    override val cloudActionDontSync: String get() = context.getString(R.string.cloud_doc_action_dont_sync)
    override val cloudActionUnblock: String get() = context.getString(R.string.cloud_doc_action_unblock)
    override val cloudActionAllowSync: String get() = context.getString(R.string.cloud_doc_action_allow_sync)
    override val cloudActionRestore: String get() = context.getString(R.string.cloud_doc_action_restore)
    override val cloudActionPurge: String get() = context.getString(R.string.cloud_doc_action_purge)
    override fun cloudVersionPrefix(version: String): String = context.getString(R.string.cloud_doc_version_prefix, version)

    // Speak (Batch 6a)
    override val speakTitle: String get() = context.getString(R.string.speak)
    override val playbackSettingsTitle: String get() = context.getString(R.string.playback_settings_title)
    override val speakAndPlayEarconsTitle: String get() = context.getString(R.string.speak_and_play_earcons_title)
    override val confChangeChapter: String get() = context.getString(R.string.conf_change_chapter)
    override val confChangeTitle: String get() = context.getString(R.string.conf_change_title)
    override val confSpeakFootnotes: String get() = context.getString(R.string.conf_speak_footnotes)
    override val speakSpeedTitle: String get() = context.getString(R.string.speak_speed_title)
    override val repeatPassage: String get() = context.getString(R.string.repeat_passage)
    override val setRepeatPassageRange: String get() = context.getString(R.string.set_repeat_passage_range)
    override val speakSleepTimerTitle: String get() = context.getString(R.string.speak_sleep_timer_title)
    override val confSpeakSleepTimer: String get() = context.getString(R.string.conf_speak_sleep_timer)
    override fun sleepTimerSet(minutes: Int): String = context.getString(R.string.sleep_timer_set, minutes)
    override val speakAdvancedSettings: String get() = context.getString(R.string.speak_advanced_settings)
    override val systemSpeakSettings: String get() = context.getString(R.string.system_speak_settings)
    override val helpLabel: String get() = context.getString(R.string.help)

    override val speakSettingsTitle: String get() = context.getString(R.string.speak_settings_title)
    override val confSpeakSynchronize: String get() = context.getString(R.string.conf_speak_synchronize)
    override val confReplaceDivinename: String get() = context.getString(R.string.conf_replace_divinename)
    override val speakBookmarkingSettingsTitle: String get() = context.getString(R.string.speak_bookmarking_settings_title)
    override val confSpeakAutoBookmark: String get() = context.getString(R.string.conf_speak_auto_bookmark)
    override val confSavePlaybackSettingsToBookmarks: String get() = context.getString(R.string.conf_save_playback_settings_to_bookmarks)

    // Batch 6b — WorkspaceSelector
    override val workspaceSelectorTitle: String get() = context.getString(R.string.workspace_selector_title)
    override val giveNameWorkspace: String get() = context.getString(R.string.give_name_workspace)
    override val newCopiedWorkspace: String get() = context.getString(R.string.new_copied_workspace)
    override val deleteWorkspaceLabel: String get() = context.getString(R.string.delete_workspace)
    override val workspaceSettingsLabel: String get() = context.getString(R.string.workspace_settings)
    override val copyWorkspaceSettings: String get() = context.getString(R.string.copy_workspace_settings)
    override val copySettingsToGlobal: String get() = context.getString(R.string.copy_settings_to_global)
    override val copySettingsTitle: String get() = context.getString(R.string.copy_settings_title)
    override val copySettingsWorkspacesTitle: String get() = context.getString(R.string.copy_settings_workspaces_title)
    override val selectAll: String get() = context.getString(R.string.select_all)
    override val selectNone: String get() = context.getString(R.string.select_none)
    override val workspaceSaveChanges: String get() = context.getString(R.string.workspace_save_changes)
    override fun workspaceNumber(n: Int) = context.getString(R.string.workspace_number, n)
    override fun copyOfWorkspace(name: String) = context.getString(R.string.copy_of_workspace, name)
    override fun workspaceListingWithCurrent(name: String) = context.getString(R.string.workspace_listing_with_current, name)
}
