package net.bible.sharedui.strings

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * UI string bridge: shared composables read `LocalStrings.current.<member>`. The Android impl
 * ([AndroidStrings]) maps each member to R.string.* so res/values-* stays the single source of
 * truth (Transifex / update-translations pipeline untouched). Grows one screen at a time; the
 * iOS holder is generated by :strings-gen from the Android resources + AndroidStrings.kt.
 */
interface Strings {
    val calcWrongFormat: String
    val calcWrongFormatOperand: String
    val calcDivisionByZero: String
    // Intentionally retained to exercise the :strings-gen formatted-string generator path for iOS;
    // no composable consumes it yet (History's title is host-built).
    fun historyFor(workspace: String, window: Int): String
    val errorOccurred: String
    val okay: String
    val indexingWaitMsg: String
    val noTasksRunning: String
    val doInBackground: String

    // Batch 2 — reading plan
    val readingPlanSelectorTitle: String
    val readingPlanTitle: String
    val planDuplicateUserPlan: String
    val resetGeneric: String
    val resetPlanQuestion: String
    val yes: String
    val no: String
    val all: String
    val setCurrentDay: String
    val setStartDate: String
    val importReadingPlan: String
    val setCurrentDayQuestion: String
    val selectPassage: String
    val speak: String
    val stop: String
    val pause: String
    val done: String

    // Batch 3a — navigation choosers
    val generalBookTitle: String
    val mapTitle: String
    val dictionaryTitle: String
    val searchHint: String

    // Batch 3b — grid passage chooser
    val bible: String
    val deuterocanonical: String
    val menuAlphabetical: String
    val menuRowOrder: String
    val menuGroupByCategory: String
    val menuShowLongName: String
    val menuShowProgressBars: String

    // Batch 4 — document selection
    fun docFilterResults(count: Int): String
    val docTypeAll: String
    val docTypeBible: String
    val docTypeCommentary: String
    val docTypeDictionary: String
    val docTypeGeneralBook: String
    val docTypeMaps: String
    val docTypeAddon: String
    val languageLabel: String
    val aboutDoc: String
    val deleteLabel: String
    val deleteIndexLabel: String
    val unlockModule: String
    fun deleteDoc(name: String): String
    fun deleteSearchIndexDoc(name: String): String
    val cantDeleteDocument: String
    val downloadDocuments: String

    // Batch 4b — download
    fun moduleSizeMb(mb: Double): String
    val cancel: String
}

val LocalStrings = staticCompositionLocalOf<Strings> { error("LocalStrings not provided") }
