package net.bible.sharedui.strings

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * UI string bridge: shared composables read `LocalStrings.current.<member>`. The Android impl
 * ([AndroidStrings]) maps each member to R.string.* so res/values-* stays the single source of
 * truth (Transifex / update-translations pipeline untouched). Grows one screen at a time; the
 * iOS holder is generated by :strings-gen from the Android resources + AndroidStrings.kt.
 */
interface Strings {
    val calcWrongFormat: String
    val calcWrongFormatOperand: String
    val calcDivisionByZero: String
    // Intentionally retained to exercise the :strings-gen formatted-string generator path for iOS;
    // no composable consumes it yet (History's title is host-built).
    fun historyFor(workspace: String, window: Int): String
    val errorOccurred: String
    val okay: String
    val indexingWaitMsg: String
    val noTasksRunning: String
    val doInBackground: String

    // Batch 2 — reading plan
    val readingPlanSelectorTitle: String
    val readingPlanTitle: String
    val planDuplicateUserPlan: String
    val resetGeneric: String
    val resetPlanQuestion: String
    val yes: String
    val no: String
    val all: String
    val setCurrentDay: String
    val setStartDate: String
    val importReadingPlan: String
    val setCurrentDayQuestion: String
    val selectPassage: String
    val speak: String
    val stop: String
    val pause: String
    val done: String

    // Batch 3a — navigation choosers
    val generalBookTitle: String
    val mapTitle: String
    val dictionaryTitle: String
    val searchHint: String

    // Batch 3b — grid passage chooser
    val bible: String
    val deuterocanonical: String
    val menuAlphabetical: String
    val menuRowOrder: String
    val menuGroupByCategory: String
    val menuShowLongName: String
    val menuShowProgressBars: String

    // Batch 4 — document selection
    fun docFilterResults(count: Int): String
    val docTypeAll: String
    val docTypeBible: String
    val docTypeCommentary: String
    val docTypeDictionary: String
    val docTypeGeneralBook: String
    val docTypeMaps: String
    val docTypeAddon: String
    val languageLabel: String
    val aboutDoc: String
    val deleteLabel: String
    val deleteIndexLabel: String
    val unlockModule: String
    fun deleteDoc(name: String): String
    fun deleteSearchIndexDoc(name: String): String
    val cantDeleteDocument: String
    val downloadDocuments: String

    // Batch 4b — download
    fun moduleSizeMb(mb: Double): String
    val cancel: String

    // Batch 5 — search
    val search: String
    val emptyList: String
    val searchIndex: String
    val allWords: String
    val anyWord: String
    val phrase: String
    val searchAllBible: String
    val searchOldTestament: String
    val searchNewTestament: String
    val searchCurrentBook: String
    val chooseTranslations: String
    val recentSearches: String
    val create: String
    val rebuildIndex: String
    val openResultsInWindow: String
    fun createIndexFor(documentName: String): String
    fun rebuildIndexFor(documentName: String): String
    val rebuildIndexButton: String

    // Batch 5 (Plan B) — EPUB search
    val ftsQuery: String
    val helpFts5: String
    fun searchIn(docAbbrev: String): String
    fun searchWithResults2(count: String, docAbbrev: String): String

    // Batch 4 (remainder) — MyDocuments
    val myDocumentsEmpty: String            // R.string.my_documents_empty
    val saveAndExit: String                 // R.string.save_and_exit
    val dismiss: String                     // R.string.dismiss
    val newItem: String                     // R.string.new_item
    val importDocument: String              // R.string.my_document_import_document
    val importPage: String                  // R.string.my_document_import_page
    val newPageTitle: String                // R.string.my_document_create_page_title (menu + dialog title)
    val export: String                      // R.string.export
    val rename: String                      // R.string.rename
    val exportDocumentLabel: String         // R.string.my_document_export_document
    val editDescriptionLabel: String        // R.string.my_document_edit_description
    val noDescription: String               // R.string.my_document_no_description
    val createTitle: String                 // R.string.my_document_create_title
    val renameTitle: String                 // R.string.my_document_rename_title
    val pageRenameTitle: String             // R.string.my_document_page_rename_title
    val contentTypeLabel: String            // R.string.my_document_content_type_label
    val cannotDeleteAiDocuments: String     // R.string.my_document_cannot_delete_ai_documents
    fun newDocumentName(n: Int): String     // R.string.my_document_new_name
    fun newPageName(n: Int): String         // R.string.my_document_new_page_name
    fun deleteDocumentConfirmation(name: String): String  // R.string.my_document_delete_confirmation
    fun deletePageConfirmation(name: String): String      // R.string.my_document_page_delete_confirmation

    // Batch 4 remainder — cloud documents management
    val cloudStatusSynced: String
    val cloudStatusLocalOnly: String
    val cloudStatusCloudOnly: String
    val cloudStatusUpdate: String
    val cloudStatusBlocked: String
    val cloudStatusWontSync: String
    val cloudStatusRemoved: String
    val cloudStatusStillInstalled: String
    val cloudActionDownload: String
    val cloudActionPush: String
    val cloudActionRemoveCloud: String
    val cloudActionRemoveAllDevices: String
    val cloudActionBlock: String
    val cloudActionDontSync: String
    val cloudActionUnblock: String
    val cloudActionAllowSync: String
    val cloudActionRestore: String
    val cloudActionPurge: String
    fun cloudVersionPrefix(version: String): String

    // Speak (Batch 6a)
    val speakTitle: String
    val playbackSettingsTitle: String
    val speakAndPlayEarconsTitle: String
    val confChangeChapter: String
    val confChangeTitle: String
    val confSpeakFootnotes: String
    val speakSpeedTitle: String
    val repeatPassage: String
    val setRepeatPassageRange: String
    val speakSleepTimerTitle: String
    val confSpeakSleepTimer: String
    fun sleepTimerSet(minutes: Int): String
    val speakAdvancedSettings: String
    val systemSpeakSettings: String
    val helpLabel: String

    // Advanced Speak settings (Batch 6b)
    val speakSettingsTitle: String
    val confSpeakSynchronize: String
    val confReplaceDivinename: String
    val speakBookmarkingSettingsTitle: String
    val confSpeakAutoBookmark: String
    val confSavePlaybackSettingsToBookmarks: String

    // Batch 6b — WorkspaceSelector
    val workspaceSelectorTitle: String        // R.string.workspace_selector_title
    val giveNameWorkspace: String             // R.string.give_name_workspace (dialog title)
    val newCopiedWorkspace: String            // R.string.new_copied_workspace (clone menu label)
    val deleteWorkspaceLabel: String          // R.string.delete_workspace
    val workspaceSettingsLabel: String        // R.string.workspace_settings
    val copyWorkspaceSettings: String         // R.string.copy_workspace_settings
    val copySettingsToGlobal: String          // R.string.copy_settings_to_global
    val copySettingsTitle: String             // R.string.copy_settings_title (stage-1 dialog title)
    val copySettingsWorkspacesTitle: String   // R.string.copy_settings_workspaces_title (stage-2 dialog title)
    val selectAll: String                     // R.string.select_all
    val selectNone: String                    // R.string.select_none
    val workspaceSaveChanges: String          // R.string.workspace_save_changes (dirty-select prompt)
    fun workspaceNumber(n: Int): String       // R.string.workspace_number (new-workspace default name)
    fun copyOfWorkspace(name: String): String // R.string.copy_of_workspace (clone default name)
    fun workspaceListingWithCurrent(name: String): String  // R.string.workspace_listing_with_current
}

val LocalStrings = staticCompositionLocalOf<Strings> { error("LocalStrings not provided") }
