package net.bible.sharedui.strings

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * UI string bridge: shared composables read `LocalStrings.current.<member>`. The Android impl
 * ([AndroidStrings]) maps each member to R.string.* so res/values-* stays the single source of
 * truth (Transifex / update-translations pipeline untouched). Grows one screen at a time; the
 * iOS holder is generated by :strings-gen from the Android resources + AndroidStrings.kt.
 */
interface Strings {
    val calcWrongFormat: String
    val calcWrongFormatOperand: String
    val calcDivisionByZero: String
    // Intentionally retained to exercise the :strings-gen formatted-string generator path for iOS;
    // no composable consumes it yet (History's title is host-built).
    fun historyFor(workspace: String, window: Int): String
    val errorOccurred: String
    val okay: String
    val indexingWaitMsg: String
    val noTasksRunning: String
    val doInBackground: String
}

val LocalStrings = staticCompositionLocalOf<Strings> { error("LocalStrings not provided") }
