"""Generate the redirect-only site for the legacy docs.andbible.org host (GitHub Pages).

Every old Read the Docs URL (``/en/latest/<page>.html``) becomes a tiny stub that sends the browser to the
matching page under https://andbible.org/docs/, keeping the ``#anchor`` (old app versions hardcode such links).
``404.html`` covers other versions (``/en/stable/...``) with the same mapping rule.

Run: ``python -m sitegen.migrate.docs_stubs --out DIR``.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

from sitegen import home, paths, redirects

FIXTURE = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "rtd_urls.txt"
NEW_ROOT = f"{paths.BASE_URL}/docs/"
PREFIX = "en/latest/"

README = """# docs.andbible.org (redirects only)

The AndBible user documentation moved to https://andbible.org/docs/. Its sources now live in the
`website/` directory of https://github.com/AndBible/and-bible (AndBible/and-bible).

This repository only serves redirect stubs so that old links, including `#anchor` fragments used by older
app versions, keep working. It is generated by `python -m sitegen.migrate.docs_stubs`; do not edit by hand.
"""

# Same rule as new_path(); __PAGES__ is the JSON list of known page stems.
NOT_FOUND = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Redirecting…</title>
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=https://andbible.org/docs/">
<script>
  var known = __PAGES__;
  var m = location.pathname.match(/^\\/en\\/[^/]+\\/(.+?)(?:\\.html)?$/);
  var page = "";
  if (m && m[1] !== "index") {
    var stem = m[1].replace(/\\/index$/, "/");
    var key = stem.endsWith("/") ? stem + "index" : stem;
    if (known.indexOf(key) >= 0) page = stem.endsWith("/") ? stem : stem + "/";
  }
  location.replace("https://andbible.org/docs/" + page + location.hash);
</script>
</head><body><p>This page has moved to <a href="https://andbible.org/docs/">andbible.org/docs/</a>.</p></body></html>
"""


def legacy_pages() -> set[str]:
    """Page stems (``ai``, ``customisation/index``) of the legacy ``en/latest`` URLs in the fixture."""
    stems = set()
    for line in FIXTURE.read_text().split():
        rest = line.removeprefix(PREFIX)
        if rest.endswith(".html"):
            stems.add(rest.removesuffix(".html"))
    return stems


def new_path(old: str, pages: set[str]) -> str:
    """Site path of the new page for a legacy path relative to ``en/<version>/``.

    ``x.html`` -> ``/docs/x/``; ``d/y.html`` keeps the sub-path; ``d/index.html`` -> ``/docs/d/``;
    ``index.html`` or an empty path -> ``/docs/``. An unknown page falls back to the docs root.
    """
    stem = old.removesuffix(".html")
    if stem in ("", "index") or stem not in pages:
        return "/docs/"
    if stem.endswith("/index"):
        return f"/docs/{stem.removesuffix('index')}"
    return f"/docs/{stem}/"


def generate(out: Path) -> int:
    """Write the stub site into ``out`` (replacing its contents); returns the number of files written."""
    if out.exists():
        for child in out.iterdir():
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    out.mkdir(parents=True, exist_ok=True)
    env = home.environment()
    pages = legacy_pages()

    def write(rel: str, text: str) -> None:
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")

    for line in FIXTURE.read_text().split():
        rel = line + "index.html" if line.endswith("/") else line
        write(rel, redirects.stub_html(env, paths.BASE_URL + new_path(line.removeprefix(PREFIX), pages)))
    for rel in ("index.html", "en/index.html", "en/latest/index.html"):
        write(rel, redirects.stub_html(env, NEW_ROOT))
    write("404.html", NOT_FOUND.replace("__PAGES__", json.dumps(sorted(pages))))
    write("CNAME", "docs.andbible.org\n")
    write("README.md", README)
    return sum(1 for p in out.rglob("*") if p.is_file())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    print(f"{generate(args.out)} files written to {args.out}")


if __name__ == "__main__":
    main()
