/*
 * Copyright (c) 2026 Sykerö Software / Tuomas Airaksinen and the AndBible contributors.
 *
 * This file is part of AndBible: Bible Study (http://github.com/AndBible/and-bible).
 *
 * AndBible is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * AndBible is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with AndBible.
 * If not, see http://www.gnu.org/licenses/.
 */

package net.bible.android.database

import androidx.room.Room
import kotlinx.coroutines.runBlocking
import net.bible.android.BibleApplication.Companion.application
import net.bible.android.TEST_SDK
import net.bible.android.TestBibleApplication
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(application = TestBibleApplication::class, sdk = [TEST_SDK])
class RepoDaoTest {
    private lateinit var db: RepoDatabase

    @Before fun setUp() {
        db = Room.inMemoryDatabaseBuilder(application, RepoDatabase::class.java).allowMainThreadQueries().build()
    }

    @After fun tearDown() { db.close() }

    private fun doc(initials: String, name: String = "Name $initials", key: String? = null) =
        SwordDocumentInfo(initials, name, initials.take(3), "en", "repo", key)

    @Test fun insertReplacesOnSameInitials() = runBlocking {
        val dao = db.swordDocumentInfoDao()
        dao.insert(doc("KJV", "old"))
        dao.insert(doc("KJV", "new"))
        assertEquals(1, dao.getAll().size)
        assertEquals("new", dao.getBook("KJV")!!.name)
    }

    @Test fun listInsertAndUnlockedFilter() = runBlocking {
        val dao = db.swordDocumentInfoDao()
        dao.insert(listOf(doc("A"), doc("B", key = "secret"), doc("C")))
        assertEquals(3, dao.getKnownInstalled().size)
        assertEquals(listOf("B"), dao.getUnlocked().map { it.initials })
    }

    @Test fun updateChangesExistingRowOnly() = runBlocking {
        val dao = db.swordDocumentInfoDao()
        dao.insert(doc("A"))
        dao.update(doc("A", "renamed", "k"))
        dao.update(doc("Missing"))
        assertEquals("renamed", dao.getBook("A")!!.name)
        assertEquals("k", dao.getBook("A")!!.cipherKey)
        assertNull(dao.getBook("Missing"))
    }

    @Test fun deleteByInitialsRemovesOnlyThatDocument() = runBlocking {
        val dao = db.swordDocumentInfoDao()
        dao.insert(listOf(doc("A"), doc("B")))
        dao.deleteByOsisId("A")
        assertNull(dao.getBook("A"))
        assertEquals(listOf("B"), dao.getAll().map { it.initials })
    }

    @Test fun customRepositoryCrud() = runBlocking {
        val dao = db.customRepositoryDao()
        dao.insert(CustomRepository(name = "r1", type = "HTTPS"))
        dao.insert(listOf(CustomRepository(name = "r2", type = "FTP"), CustomRepository(name = "r3", type = "FTP")))
        val all = dao.all()
        assertEquals(setOf("r1", "r2", "r3"), all.map { it.name }.toSet())
        assertTrue("autogenerated ids are distinct", all.map { it.id }.toSet().size == 3)

        val r1 = all.single { it.name == "r1" }
        dao.update(r1.copy(host = "example.org"))
        assertEquals("example.org", dao.all().single { it.name == "r1" }.host)

        dao.delete(r1)
        assertEquals(setOf("r2", "r3"), dao.all().map { it.name }.toSet())
    }

    @Test fun customRepositoryNameIsUnique() {
        val dao = db.customRepositoryDao()
        runBlocking { dao.insert(CustomRepository(name = "dup", type = "FTP")) }
        val failed = runCatching { runBlocking { dao.insert(CustomRepository(name = "dup", type = "FTP")) } }
        assertTrue("unique index on name must reject duplicates", failed.isFailure)
        assertEquals(1, runBlocking { dao.all().size })
    }
}
