openMyNotes: Open in My Notes window
openStudyPad: Open in Study Pad window (%s)
noteText: Footnotes (%s)
crossReferenceText: Cross references
findAllOccurrences: Find all occurrences
reportError: Report an error
errorTitle: Error occurred
warningTitle: Warning
normalTitle: Please note
footnoteTypeUndefined: Undefined type
footnoteTypeStudy: Study
footnoteTypeExplanation: Explanation
footnoteTypeVariant: Variant
footnoteTypeAlternative: Alternative
footnoteTypeTranslation: Translation
clearLog: Clear error log
editNote: Edit
editNotePlaceholder: Edit a note for bookmark
editTextPlaceholder: Tap to edit text
inputPlaceholder: Write here
inputReference: Give bible reference
assignLabels: Labels
bookmarkAccurate: Bookmark was created in %s
bookmarkInaccurate: Bookmark book information not stored, content is displayed in %s.
defaultBook: default bible document
ok: OK
yes: Yes
ambiguousSelection: Which one of these do you wish to do?
cancel: Cancel
removeBookmarkConfirmationTitle: Remove bookmark?
removeBookmarkConfirmation: Are you sure you want to remove bookmark?
closeModal: Close
createdAt: "Created: %s"
lastUpdatedOn: "Last updated: %s"
strongsLink: Open Strongs
studyPadLink: Open study pad
externalLink: Open external link
referenceLink: Open reference link
openFootnote: Open footnote
openBookmark: Open bookmark (%s)
noMyNotesTitle: No My Notes for this chapter.
noMyNotesDescription: >
  Get started by creating bookmarks in bible document,
  they will appear here and you can add to them your personal notes.
emptyStudyPad: >
  Empty study pad. Start writing study pad by adding text entries
  and creating bookmarks with this bookmark label.
studyPadModalTitle: Edit study pad entry
doYouWantToDeleteEntry: Are you sure you want to delete this study pad entry?
removeStudyPadConfirmationTitle: Remove study pad entry?
dragHelp: You can drag & drop item to re-order study pad
saved: saved
openAll: Open all references
editBookmarkPlaceholder: Tap to edit My Notes for this bookmark
onlyLabel: Only label
wholeBookmark: Whole bookmark
otherNoteText: Other note
assignLabelsMenuEntry: Assign labels
jumpToStudyPad: Jump to Study Pad
