# Open in "My Notes" title. (just demonstrating developer note)
bookmarks: Bookmarks
bookmarksAndNotes: Bookmarks & My Notes
openMyNotes: Open in My Notes
openStudyPad: Open in Study Pad (%s)
noteText: Footnotes (%s)
noteTextWithoutType: Footnotes
crossReferenceText: Cross references
findAllOccurrences: Find all occurrences
reportError: Report an error
errorTitle: Error occurred
warningTitle: Warning
normalTitle: Please note
footnoteTypeStudy: Study
footnoteTypeExplanation: Explanation
footnoteTypeVariant: Variant
footnoteTypeAlternative: Alternative
footnoteTypeTranslation: Translation
clearLog: Clear error log
editTextPlaceholder: Tap to edit text
inputPlaceholder: Write here
inputReference: Enter Bible reference
invalidReference: Verse not found
bookmarkAccurate: Bookmark was created in %s
bookmarkInaccurate: Bookmark book information not stored, content is displayed in %s.
defaultBook: default Bible document
ok: OK
yes: "Yes"
ambiguousSelection: Which action do you wish to take?
cancel: Cancel
removeBookmarkConfirmationTitle: Remove bookmark?
removeBookmarkConfirmation: Are you sure you want to remove this bookmark?
createdAt: "Created: %s"
lastUpdatedOn: "Last updated: %s"
strongsAndMorph: Definition & Morphology
externalLink: Open external link
referenceLink: Open reference link
openFootnote: Open footnote
noMyNotesTitle: No My Notes for this chapter.
noMyNotesDescription: >
  Get started by creating bookmarks in a Bible document.
  The bookmarks will then appear here and you can add your personal notes to them.
emptyStudyPad: >
  Empty study pad. Start adding to this study pad by creating text entries here
  or by creating bookmarks with a bookmark label that corresponds with this study pad.
doYouWantToDeleteEntry: Delete this study pad entry?
removeStudyPadConfirmationTitle: Remove study pad entry?
dragHelp: Drag to reorder
openAll: Open all references
editBookmarkPlaceholder: Tap to edit My Notes for this bookmark
onlyLabel: Only label
wholeBookmark: Whole bookmark
assignLabelsMenuEntry1: Select or edit labels…
favouriteLabels: Favourite Labels
recentLabels: Recent Labels
bookmarkLabels: Bookmark labels
refParserHelp: Please install %s module to use references in languages other than English.
openDownloads: Go to Add-on downloads
verseShare: Share
verseSpeak: Speak
verseCompare: Compare
verseMemorize: Memorize
verseNote: Note
verseMyNotes: My Notes
verseParagraphBreak: Paragraph
verseShareLong: Share this verse
verseCompareLong: Compare verse
verseMemorizeLong: Memorize Bible verses
verseNoteLong: Write a note
verseParagraphBreakLong: Paragraph break
addBookmark: Bookmark
selectCustomIconTitle: Select custom marker icon
bookmarkSettingsTitle: Configure bookmark settings
subtitlePlaceholder: Subtitle text
customIconLabel: Custom icon
editActionLabel: Edit action
editActionModeLabel: Mode
editActionModeNone: None
editActionModeAppend: Append text
editActionModePrepend: Prepend text
editActionContentLabel: Content
editActionContentPlaceholder: Enter text to be added to document...
experimentalFeatureTitle: Experimental
experimentalFeatureHelpTitle: About Experimental Features
experimentalFeatureHelpContent: Experimental features are new capabilities that are still being developed and tested. They may not work perfectly and could change significantly or be removed in future app versions.
insertParagraphBreak: Insert paragraph break
insertSubtitle: Insert subtitle
xmlParseError: XML parsing error
invalidTag: Invalid tag
invalidClosingTag: Invalid closing tag
unmatchedClosingTag: Unmatched closing tag
unclosedTag: Unclosed tag
unknownError: Unknown error
blur: Blur
reset: Reset
peek: Peek
wordBlur: Word Blur
wordScramble: Word Scramble
more: More
