name: Run tests

on:
  push:
    branches: 
      - develop
      - 'current-stable'
      - 'release/*'
    paths:
      - '**/*.java'
      - '**/*.kt'
      - '**/*.kts'
  pull_request:
    paths:
      - '**/*.java'
      - '**/*.kt'
      - '**/*.kts'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10 # so that recent tags can be found
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11' # later than 1.8 not working with roboelectric as of 2020-06-15

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: '14'
    - name: Cache gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Cache test modules
      id: cache-test-modules
      uses: actions/cache@v2
      with:
        path: ~/.sword
        key: ${{ runner.os }}-test-modules # cache auto-removes if not accessed in 7 days. If data needs to refresh, change key name here (till https://github.com/actions/cache/issues/2 is addressed)

    - name: Download test modules if not cached
      if: steps.cache-test-modules.outputs.cache-hit != 'true'
      run: |
        wget ${{ secrets.DOWNLOAD_TEST_MODULES_URL }} -O ./testmods.zip.enc
        openssl enc -in ./testmods.zip.enc -out ./testmods.zip -d -aes-256-cbc -pbkdf2 -pass 'pass:${{ secrets.TEST_MODULE_ENCRYPTION_KEY }}'
        mkdir -p $HOME/.sword
        unzip -o -d $HOME/.sword ./testmods.zip

    - name: Build with Gradle
      run: ./gradlew --console plain testStandardRelease

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: test-results
        path: app/build/reports/**/*.html
        retention-days: 5

    - name: Before saving cache
      run: |
        rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        rm -fr $HOME/.gradle/caches/*/plugin-resolution/
